# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `booleans` gem.
# Please instead update this file by running `bin/tapioca gem booleans`.


# source://booleans//lib/booleans/version.rb#3
module Booleans; end

# @return [String]
#
# source://booleans//lib/booleans/version.rb#5
Booleans::VERSION = T.let(T.unsafe(nil), String)

class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin

  private

  # source://booleans//lib/booleans.rb#12
  def Boolean(val); end
end
