inherit_gem:
  rubocop-espago: sorbet.yml

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - lib/tapioca/**/*.rb

Style/DocumentationMethod:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Sorbet/ForbidTSig:
  Enabled: false

Sorbet/RedundantExtendTSig:
  Enabled: false

Sorbet/ForbidMixesInClassMethods:
  Enabled: false

Sorbet/ForbidTUnsafe:
  Enabled: false

Sorbet/ForbidTHelpers:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false
